# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec7054dffeb831f0d38b0cef106f2eb7f897192d46215d1ffdea672eba995ed2fa2b7d657c49e5b1ca15baa56d191d7e9f5424054032ab3f35c206a523ae941d

test:
  secret_key_base: d2c9d1a48d32757cf56bc58cc70839d14ac8ec1138d1aac6cd9766238481e52d0c9238a2db4d0a38e66460aa9094decc2efd6002a3691e1aee1ddd166f2ba5c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
